name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          gem install rails

      - name: Check installations
        run: |
          ruby -v
          bundle exec rails -v

      - name: Make bin/rails executable
        run: chmod +x bin/rails

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run tests
        run: bundle exec rails test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          gem install rails
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop
      - name: Make binstubs executable
        run: |
          chmod +x bin/brakeman
          chmod +x bin/rubocop
          chmod +x bin/bundler-audit
      - name: Security audit dependencies
        run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2
      - name: Lint Ruby files
        run: bin/rubocop --parallel