name: "Ruby on Rails CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          gem install rails

      - name: Check installations
        run: |
          ruby -v
          bundle exec rails -v

      - name: Make bin/rails executable
        run: chmod +x bin/rails

      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run tests
        run: bundle exec rails test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          gem install rails
          gem install brakeman
          gem install rubocop
          gem install bundler-audit
      - name: Security audit dependencies
        run: bundle exec bundler-audit --update
      - name: Security audit application code
        run: bundle exec brakeman -q -w2
      - name: Lint Ruby files
        run: bundle exec rubocop --parallel --autocorrect --disable-uncorrectable

  rspec-test:
    name: RSpec
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.4
          bundler-cache: true
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          gem install rails
          gem install rspec
          gem install rspec-rails
      - name: Set up database
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Run RSpec tests
        run: bundle exec rspec
  
  deploy:
    runs-on: ubuntu-latest
    # needs: [ test, lint, rspec-test ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up environment variables
        env:
          # These are GitHub secrets
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

        run: |
          # Save the SSH private key and set permissions
          echo "$SSH_PRIVATE_KEY" > final-attempt.pem

          # Set read and write permissions for owner
          chmod 600 final-attempt.pem

      - name: Deploy to EC2
        run: |
          #Define EC2 instance details
          INSTANCE_ID="i-0f0354c44ab34cae0"

          # Elastic IP for instance
          PUBLIC_IP=44.222.60.79

          #SSH into EC2 instance
          #StrictHostKeyChecking=no - disables identity verification

          ssh -o StrictHostKeyChecking=no -i final-attempt.pem ubuntu@$PUBLIC_IP << 'EOF'
            # Exit if error occurs
            set -e
            export PATH="$HOME/.rbenv/bin:$PATH"
            eval "$(rbenv init -)"
            # Navigate to project directory
            cd WhatToWatch
            echo "PATH is: $PATH"
            # Pull latest changes from GitHub
            git pull origin master
            # Install dependencies
            bundle install
            # Run migrations in the PRODUCTION environment
            rails db:migrate
            # Start the Rails server, workflow runs until server is terminated
            nohup sudo /home/ubuntu/.rbenv/shims/rails server --binding 0.0.0.0 --port 80 > /dev/null 2>&1 &
          EOF

      - name: Clean up
        run: |
          # Remove the SSH private key after its use
          rm final-attempt.pem